eureka:
  client:
    enabled: false

spring:
  cloud:
    openfeign:
      client:
        config:
          user-service:
            url: ${SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_USER_SERVICE_URL:http://user-service:8080}

