spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    open-in-view: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: ${SERVER_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
    ip-address: ${EUREKA_INSTANCE_IP_ADDRESS}
    hostname: ${EUREKA_INSTANCE_HOSTNAME}



auth:
  jwt:
    issuer: ${AUTH_JWT_ISSUER}
    secret: ${AUTH_JWT_SECRET}
    access-token-expiration: ${AUTH_JWT_ACCESS_TOKEN_EXPIRATION}
    refresh-token-expiration: ${AUTH_JWT_REFRESH_TOKEN_EXPIRATION}
  google:
    client-id: ${AUTH_GOOGLE_CLIENT_ID}
  redis:
    refresh-token-key-prefix: ${AUTH_REDIS_REFRESH_TOKEN_KEY_PREFIX}
  cookie:
    refresh-token-name: ${AUTH_COOKIE_REFRESH_TOKEN_NAME}
    secure: ${AUTH_COOKIE_SECURE}
    http-only: ${AUTH_COOKIE_HTTP_ONLY}
    same-site: ${AUTH_COOKIE_SAME_SITE}
    path: ${AUTH_COOKIE_PATH}
    domain: ${AUTH_COOKIE_DOMAIN}
  rate-limit:
    login-register:
      enabled: ${AUTH_RATE_LIMIT_LOGIN_REGISTER_ENABLED}
      capacity: ${AUTH_RATE_LIMIT_LOGIN_REGISTER_CAPACITY}
      refill-tokens: ${AUTH_RATE_LIMIT_LOGIN_REGISTER_REFILL_TOKENS}
      refill-duration: ${AUTH_RATE_LIMIT_LOGIN_REGISTER_REFILL_DURATION}
      key-prefix: ${AUTH_RATE_LIMIT_LOGIN_REGISTER_KEY_PREFIX}

  # OTP Config (Forgot/Change Password)
  otp:
    length: ${AUTH_OTP_LENGTH}
    ttl: ${AUTH_OTP_TTL}
    forgot-password-key-prefix: ${AUTH_OTP_FORGOT_KEY_PREFIX}
    change-password-key-prefix: ${AUTH_OTP_CHANGE_KEY_PREFIX}

  # Email Verify Config
  verify-email:
    token-ttl: ${AUTH_VERIFY_TOKEN_TTL}
    key-prefix: ${AUTH_VERIFY_KEY_PREFIX}

  # RabbitMQ event publishing
  rabbitmq:
    critical-exchange: ${AUTH_RABBITMQ_CRITICAL_EXCHANGE}
    notification-exchange: ${AUTH_RABBITMQ_NOTIFICATION_EXCHANGE}
    routing:
      email-verify: ${AUTH_RABBITMQ_ROUTING_EMAIL_VERIFY}
      email-otp: ${AUTH_RABBITMQ_ROUTING_EMAIL_OTP}
      account-created: ${AUTH_RABBITMQ_ROUTING_ACCOUNT_CREATED}

management:
  endpoints:
    web:
      exposure:
        include: health,info

